apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "gate.fullname" . }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.cluster-issuer }}
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: gate-tls
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "gate.fullname" . }}
            port: 
              number: 80

